# Generated by Django 3.2.25 on 2024-06-18 15:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('natureza', models.CharField(choices=[('saida', 'Saída'), ('entrada', 'Entrada')], max_length=7)),
                ('tipo', models.CharField(choices=[('pix', 'PIX'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('dinheiro', 'Dinheiro'), ('boleto', 'Boleto'), ('outros', 'Outros')], max_length=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descontrole.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Estimativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)])),
                ('ano', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2024)])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('natureza', models.CharField(choices=[('saida', 'Saída'), ('entrada', 'Entrada')], max_length=7)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descontrole.categoria')),
            ],
        ),
    ]
