# Generated by Django 3.2.25 on 2024-06-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descontrole', '0007_auto_20240623_1929'),
        ('descontrole', '0008_auto_20240623_2017'),
    ]

    operations = [
    ]
