# Generated by Django 3.2.25 on 2024-07-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('descontrole', '0030_auto_20240723_2256'),
        ('descontrole', '0030_auto_20240724_0804'),
    ]

    operations = [
    ]
